version = 0.1
[default.deploy.parameters]
stack_name = "tiktokdownloader-medium"
resolve_s3 = true
s3_prefix = "tiktokdownloader-medium"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
